# Makefile to build p4 program

.DEFAULT_GOAL := build

build:
	@echo "make <target>"

01:
	@echo "make 01"
	p4c --std p4_16 -b bmv2 --p4runtime-files build.bmv2/example01.p4info.txt -o build.bmv2 example01.p4
